export { default as Tabs } from "./tabs.svelte";
export { default as TabsContent } from "./tabs-content.svelte";
export { default as TabsList } from "./tabs-list.svelte";
export { default as TabsTrigger } from "./tabs-trigger.svelte";
export { type TabsContext } from "./context";
export { tabsFrame, type TabsVariant, type TabsSize } from "./variants";
export { default as Root } from "./tabs.svelte";
export { default as Content } from "./tabs-content.svelte";
export { default as List } from "./tabs-list.svelte";
export { default as Trigger } from "./tabs-trigger.svelte";
